### PR TITLE
restart module for v0.2

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
I also want to revise the heuristic to adapt names to be "idiomatic Go" before we cut a release.

**Comment by warpfork** [comment]
Okay, so I did two passes of review here, and I'll start with the distilled big stuff, and then also share the (fairly unfiltered) bullet points of why I came to those distilled questions.  You can ignore the latter if you like.

And you can also ignore this whole review, if you like.  I'm perfectly willing to let these all be considered "nits" and let you take on maintainership and do as you like with this.

---

**distilled**:

Big Q 1: Do we want to do anything about multicodecs being a subset of what's present in multiformats table?

This generator currently emits the whole multiformats table.  This has some interesting outcomes, such as for example "sha2-512" (which I think we would say: **is** a multihash; **is** a multiformat (since that's a superset of multihash); is **not** a multicodec) shows up in this output.

It may be difficult to do something about this without gardening the multiformats csv file that's the input to this process.  I don't know if we want to recurse into that.  But it would be nice to have a short conversation about whether we expect to review that table; if we might release a future version of this library which has fewer exported symbols because of filters we might add to trim it down to multicodecs only; etc; and maybe drop a short notice about that into the README.

Big Q 2: Do we want to use the Stringer tool... or should we apply the "a little copying is better than a little dependency" rule-of-thumb, and make things a little more polished by integrating a stringer-like behavior ourselves?

I think I'd rather the latter.  We've already got templates here, so it's not a big pull.  It saves us from having a dependency on a thingamawajit that's not in the repo.  And I think we'd actually get cleaner output from the effort: specifically, we could generate _only_ the comments that come before the declarations, and skip the end of line comments (which, iiuc, exist only to ferry data to the stringer tool); to me, this would read a lot cleaner.

But, again: I think the person writing this code has more sway than me about how much work goes into this, so this is my opinion, but I'll readily defer.

---

**raw discovery log**: (you can ignore this, but it was how I processed the data, so I'm likely to refer to it myself if you ask me why I came to any of the distilled thoughts, and I might as well share):

- what is going on with these tags
	- quick examples:
		- messagepack is "serialization" but json is "ipld"?
		- json is "ipld" and cid is also "ipld"?
	- several concerns here:
		- the word "codec" isn't showing up a lot at all
		- the things that i would say are codecs are not consistently sharing a tag
		- the things that i would say are codecs are sharing tags with other things that i would say are not codecs
	- this is not a new problem, but rather comes from the multiformats input csv.
		- i'm concerned that the input csv might be a bit of a weedpatch.
		- as we discussed in the [2020-10-22 specs synchronous](https://github.com/ipld/team-mgmt/blob/master/meeting-notes/2020/2020-10-22--ipld-specs.md#what-do-we-think-multicodec-means-anyway), there's broad agreements that we should start consistently talking about codecs, and multicodecs indicators being a subset of multiformats indicators
		- so the question is: what do we do about it?
			- do we want to emit a new piece of work which repeats this questionable data in a new and shiny-looking place?
			- do we want to sit on our hands about emitting go symbols until after we can do more gardening of that input table and its tags?  (is that even possible to expect will happen?  I've heard that there are inertia around that csv file.)
			- is there going to be possibility that we'll remove entries from the constants currently generated, if we include everything now, and add a subset filter later?

- nit: i'd like to put all generated comments either on end-of-entry or before-entry -- not both
- nit: if we're doing comment-before-entry, i'd like to put an empty line between each comment+entry.

- the ""invalid array index" compiler error" is a facinating trick but do we really care about this?
	- this is defending against someone regenerating one file and not the other...?  that seems like a somewhat strange thing to do defense-in-depth against?  (am I missing something here?)

- the `_Codec_name` being a giant concat... is there a document that describes the reasoning for this somewhere?
	- i see how it works but it seems very... clever
	- i don't think this makes the source form any shorter
	- is it aiming to shrink binary size somehow?
	- does all that substringing make init time longer?  or does it make it shorter by requiring less getting of addresses from the binary constants?  what's the aim here
	- warpfork learning moment: wow, is this what the common stringer tool does?  my goodness
		- [yes, yes it is](https://github.com/golang/tools/blob/78b158585360beccadc3faac6e35759f491831f3/cmd/stringer/stringer.go#L544)
			- and no, I don't see reasons why really documented in that code, either

- I am not really fond of this reference to `stringer` in the gen instructions being a reference to something not in the repo.
	- I don't have this in my $PATH.  Sorry.  What can I say?  I just don't.  I don't put dev dependencies in my global $PATH no matter how helpful they are.
	- I'm probably willing to shrug on this if you feel strongly about it, just because I don't expect to regenerate this too often, and so the intensity of my concern is low.  But if it's low effort to avoid this dependency, I'd be a fan.
	- warpfork learning moment: I just realized this is also why there's two different formats of comments per entry.  the stringer tool asks for EOL format.  oi.  okay.

---

At any rate!  It's cool that we're getting some nice clean generated constant tables for this stuff.  :+1:

**Comment by rvagg** [comment]
> what is going on with these tags

There's a general agreement within multiformats as far as I can tell that we all think the "tag" field is a mess and needs to be reworked or removed at some point. So as long as this tag isn't showing up in actual code then I think we're fine here. Since they're just showing up in comments I think that's fine because it gives us the breathing room to figure out categorisation properly in multiformats.

**Comment by mvdan** [comment]
> Big Q 1: Do we want to do anything about multicodecs being a subset of what's present in multiformats table?

Hm, I hadn't thought about that. The intent is to emit the entire table. Perhaps we should abandon this repo after all and just create `go-multiformats`? I would find it less useful to have entirely separate modules for go-multicodec, go-multihash, etc (and also more work!).

> Do we want to use the Stringer tool

Yes; it's pretty efficient and does smart things, like fail to compile if the strings don't align with the integer constants. We could write the code ourselves, yes, but we'd either lose efficiency, or have to reimplement those extra hundred lines of code. I think that's well beyond "a little copying", especially given how stringer is just part of x/tools.

**Comment by mvdan** [comment]
> nit: if we're doing comment-before-entry, i'd like to put an empty line between each comment+entry.

Sure.

> this is defending against someone regenerating one file and not the other...?

Yes. For example, if one runs `go run gen.go` but doesn't run `stringer`. You can say this wouldnt' be a problem if we used a single generator, but that goes back to not wanting to reimplement the efficient stringer generation.

> the `_Codec_name` being a giant concat... is there a document that describes the reasoning for this somewhere?

This is the efficiency :) Fewer symbols, less generated code, less memory usage (since the strings are tightly packed). This does matter when there are many enum values, which is the case here.

> I am not really fond of this reference to `stringer` in the gen instructions being a reference to something not in the repo.

Me neither to be honest, but there isn't a good solution right now. Ideally, we'd just do:

```
//go:generate go run golang.org/x/tools/cmd/stringer@some-commit [args...]
```

This would work because it would pin a specific version, not use `PATH` in any way, and it wouldn't force us to add the `x/tools` module in `go.mod`. That last point is IMO important, because this should be a very, very small module to just export a bunch of constants.

Such `go run external-main@version` isn't implemented right now, so we can either reimplement the same behavior ourselves (via a script, or by adding x/tools to go.mod, which we don't want to do), or to fall back to the old behavior of depending on PATH. Given that `stringer` changes very slowly, I think just doing the silly thing is "okay enough" for now :) If someone has repeated issues with this method, I'm happy to do something a bit better.

**Comment by mvdan** [comment]
Thanks for the reviews! I will deal with the bits of non-idiomatic Go in a follow-up PR, including the weird comment spacing and the weird name heuristic.

**Pull request merged**
