### PR TITLE
replace Of with Code.Set, implementing flag.Value

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by willscott** [comment]
are you going to handle up-streaming this api change into where we currently use `Of` in the `ipld-in-ipfs` branch of ipfs?

**Review by willscott — APPROVED** [review]

**Comment by mvdan** [comment]
Yep, sure - could you please point me in the direction of the branch? We had multiple ipld-in-ipfs branches, and I don't recall where you ended up using Of.

**Comment by willscott** [comment]
https://github.com/ipfs/go-ipfs/blob/feat/dag-put-ipld-prime/core/commands/dag/put.go#L52 (for both `get` and `put` in that directory) are where i've used it.

**Comment by mvdan** [comment]
Done in https://github.com/ipfs/go-ipfs/commit/fcae03f58aba40e85f1a189e38cf82a3844d8660 after the two PRs.

**Pull request merged**
